const colors = {
  light: {
    text: "#111122",
    tint: "#1C1C7D",
    background: "#F7F7FC",
    foreground: "#111122",
    card: "#FFFFFF",
    cardForeground: "#111122",
    primary: "#1C1C7D",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF0FB",
    secondaryForeground: "#1C1C7D",
    muted: "#F0F0F8",
    mutedForeground: "#6E6E8A",
    accent: "#E8E8FA",
    accentForeground: "#1C1C7D",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E2E2EE",
    input: "#E8E8F4",
    success: "#059669",
    successForeground: "#FFFFFF",
    warning: "#D97706",
    warningForeground: "#FFFFFF",
  },
  dark: {
    text: "#F0F0FF",
    tint: "#7C7CFF",
    background: "#070710",
    foreground: "#F0F0FF",
    card: "#0F0F1E",
    cardForeground: "#F0F0FF",
    primary: "#6366F1",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A30",
    secondaryForeground: "#C8C8FF",
    muted: "#14142A",
    mutedForeground: "#8888AA",
    accent: "#1E1E38",
    accentForeground: "#A0A0FF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E3A",
    input: "#1A1A30",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
